language: python
# command to install dependencies
install: "make"
# command to run tests
script:
  - make ci
cache: pip
jobs:
  include:
    - stage: test
      python: '3.5'
    - stage: test
      python: '3.6'
    - stage: test
      python: '3.7'
      dist: xenial   
    - stage: coverage
      python: '3.6'
      script: coverage
