language: python
install: make
script:
- make ci
cache: pip
jobs:
  include:
  - stage: test
    python: '3.6'
  - stage: test
    python: '3.7'
    dist: xenial
  - stage: coverage
    python: '3.6'
    script: coverage
  #- stage: build # This stage builds and lints in parallel
    #if: (branch = master)
    #name: Build
    #script: cd docs && make html && cd ../ # build the docs
  - stage: deploy
    #name: Deploy to GitHub Pages
    #if: (NOT type IN (pull_request)) AND (branch = master) # only deploy if merging on master
    before_deploy: cd docs && make html && cd ../
    deploy:
      - provider: pages # deploy on github pages
        skip_cleanup: true
        github_token:
          secure: FYb0hUTk1aaDPGaooXkRGHMgYJTom1ZrQ0J+RqWnAS6bH47vDQuE2uXw0iFJNBMMRMVSL0gZ7LwZpRPs3Mvi9i6tNbLcOMqf8xaBG3k4XTCffIjo9xMU09KuAjInOA2rLlo/Rh6d1ARYoxnC4FFlAv53dRDUXqTtJkXmuVI5/f1oMwxdNg0TyJk3dFdXjIFjvMjVG4WuUyYWGLvO2BU/QNpMz4+tJlRvyxdjUoxB6RX05+whIJ2vD3wq8WABzR6VJDDFWuS2j5XDsI7tGw0d1/3ntUHD/HYFs6kJzxbMf3SS8ihDq2VBskl79ZV9Q/oNP73jC6kq0B940q4z/GGNvz83GJbqTHx0iA7oLgWegGivGaoIvzUuzPKwOjw9FEoGVuFtPjFnz8XOGRzdVWWjikMFd3beXNvhnCgNiyGt8uXLaQkrimbu32H4eZUEAtz0njNk40N5XNdZ0ytTBSvD27SS+TQWG3ZsiLpDvuiPfDrHs20Q1RvgIjjmB2ZslftVNdKrR+t56BhE3tec5YpPYKBkVRshn7QN37QnVRKXuPCjjnJSjFZNybPRPtWCWSe7kSZbKyrOR5ZxanoaKP4PW7yuZqSL2+PAK8HJPLpuFeNkzBDO6qx58eLOjLe9THxpWTc29CSUBBvGjXJ26f3vmOTuntKjbPW/aYLQ5+8WK4g=
        local_dir: docs/build/html
        on:
          branch: master
      - provider: pypi
        user: __token__
        password:
          secure: CBprpI5MpbgeReYOKTP8Ke/J+dC+eoDd5WEY5Tj/BpJ9v6mDIYHBhv4b5WudzaEcytEoBdEhSGM/elalJStHtPvIz8i2Di5zAnjQAo3uX3/R9uV50MdbiDIobpM617zmh2eYYwkBmVUZxm5ENzXoMUwAOFl0abEu+z+mYz3cd+zO1dm/T047mbyUn1hxwUflMejRp4oVoamtnRRd8v9E7QWh3scqIrsSYQnxMUvKr3AabkjxFwfN4PNcRNCWsqviU3jNEqwWUOGc7fMNAJBdFsr7ENm4/a432NN+ocRqq0OMpzOL7LBC9ZsEGPTCtLZPVfJ11Yo9zAMAgh+DFRxkp3jgToAjHehFs0j0XIqnux0l3ezQl2GqXosdLfdsTCcKtEW2hoH+2dpkc1p41xe6s208E/pwD1FZfPPmlDvXiSc0rB6MNgMEGq6Vf3cQFay1tfMHxydYT/hlGKg3eUx13+V0H8l8eSFxMTLYa+5btg8hUvbdEU6ET5MUxzY7hCVl3fHMacdsC+oz53ddBv+h+DlCS8wPeiFG7sWRzBWEizk/EJgLwkFIigqHq1RYZsq4GlXFdsrqgeIITcxbXARtnXz3UJONhdMqeBpfxc84maB46HKE2bohQvHbm+n2u2N05vMUMuFyOG6M7DLeLWlbpKGhMDMgPeRhBYT89E9QR88=
        on:
          tags: true
        skip_existing: true
